// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg6ykNzTYSgO9Vz2dJEGnqUXiDNXLD15w',
    appId: '1:584069298155:web:8cd895e31beb0612218bae',
    messagingSenderId: '584069298155',
    projectId: 'flutter-33a0f',
    authDomain: 'flutter-33a0f.firebaseapp.com',
    storageBucket: 'flutter-33a0f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgOWmCVG2Dq4nYCtZw7lP0z1TP_vUOd4U',
    appId: '1:584069298155:android:e891634371e8edd6218bae',
    messagingSenderId: '584069298155',
    projectId: 'flutter-33a0f',
    storageBucket: 'flutter-33a0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABvIZEM7pxbj_yrtYiR0Mzd6iLKK4z5hg',
    appId: '1:584069298155:ios:394194a4f9c5f2f8218bae',
    messagingSenderId: '584069298155',
    projectId: 'flutter-33a0f',
    storageBucket: 'flutter-33a0f.firebasestorage.app',
    iosBundleId: 'com.example.busTimetableApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABvIZEM7pxbj_yrtYiR0Mzd6iLKK4z5hg',
    appId: '1:584069298155:ios:394194a4f9c5f2f8218bae',
    messagingSenderId: '584069298155',
    projectId: 'flutter-33a0f',
    storageBucket: 'flutter-33a0f.firebasestorage.app',
    iosBundleId: 'com.example.busTimetableApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg6ykNzTYSgO9Vz2dJEGnqUXiDNXLD15w',
    appId: '1:584069298155:web:d32bdac9d02a2830218bae',
    messagingSenderId: '584069298155',
    projectId: 'flutter-33a0f',
    authDomain: 'flutter-33a0f.firebaseapp.com',
    storageBucket: 'flutter-33a0f.firebasestorage.app',
  );

}